# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  opentelemetrywithaspiredashboard:
    image: opentelemetrywithaspiredashboard
    container_name: api 
    build:
      context: .
      dockerfile: OpenTelemetryWithAspireDashboard/Dockerfile
    ports:
      - 5138:5138
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://coffeeshopDashboard:18889
    networks:
     - otel  

  coffeeshopDashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard 
    ports:
      - 18888:18888
    networks:
      - otel

networks:
  otel:
